// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoK0mIbqJsa9ZeMrUU4UfMUKXzMahekwM',
    appId: '1:966857592415:web:c5e82a2ca11e1e69a4d5ea',
    messagingSenderId: '966857592415',
    projectId: 'medx-2d235',
    authDomain: 'medx-2d235.firebaseapp.com',
    storageBucket: 'medx-2d235.firebasestorage.app',
    measurementId: 'G-9TCLFPD5GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC69S33BEMtP3fepWU6vOqJ_hLOIovcDSQ',
    appId: '1:966857592415:android:97308d4cda4de7ffa4d5ea',
    messagingSenderId: '966857592415',
    projectId: 'medx-2d235',
    storageBucket: 'medx-2d235.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZj4CVA2bG1_FQk8TrfSc6N2zMh8aOW_I',
    appId: '1:966857592415:ios:afda4839916d3300a4d5ea',
    messagingSenderId: '966857592415',
    projectId: 'medx-2d235',
    storageBucket: 'medx-2d235.firebasestorage.app',
    iosBundleId: 'com.example.medx',
  );
}
